version: 0.0
os: linux
files:
   - source: target/petclinic.war
     destination: /usr/share/tomcat7/webapps
permissions:
   - object: /usr/share/tomcat7/webapps
     pattern: "**"
     owner: ec2-user
     group: ec2-user
     mode: 755
     type:
       - file